# Generated by Django 5.0.4 on 2024-04-09 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
